import { Schema } from "mongoose";

export const ProjectSchema = new Schema({    
    idConcurso:{
        type:String,
        required:true
    },
    nombreConcurso:{
        type:String,
        required:false
    },
        nombreProyecto:{
            type:String,
            require:true,
        },
        nombreGrupo:{
            type:String,
            require:true,
        },
        encargado:{
            type:String,
            required:true
        },
        ciclo:{
            type:String,
            required:true,
        },
        curso:{
            type:String,
            required:true,
        },
        docente:{
            type:String,
            required:true,
        },
        estudiantes:{
            type:Array,
            required:true
        },
        categoria:{
            type:String,
            required:true,
        },
        estado:{
            type:String,
            default:"false"
        },
        path:{
            type:Array,
            required:true
        },
        github:{
            type:String,
            required:true
        },
        createdAt:{
            type:Date,
            default:Date.now
        },
        concurso:{
            type:String,
            required:true
        }
})